# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PushIOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PushIOS

  target 'PushIOS-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PushIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PushIOS-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
end
